[package]
name = "telegram_system"
version = "0.1.0"
edition = "2021"
authors = ["krozzzis"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
timetable_system = { path = "../timetable_system" }


[dependencies.teloxide]
version = "0.11.3"
features = ["macros"]
